<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>ClientPlugin</RootNamespace>
    <AssemblyName>Prism.SSGI</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <DefineConstants>$(DefineConstants);DEV</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HavokWrapper">
      <HintPath>$(Bin64)\HavokWrapper.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="netstandard" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(Pulsar)\Libraries\Legacy\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.Common">
      <HintPath>$(Bin64)\Sandbox.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.Game">
      <HintPath>$(Bin64)\Sandbox.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.Graphics">
      <HintPath>$(Bin64)\Sandbox.Graphics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.RenderDirect">
      <HintPath>$(Bin64)\Sandbox.RenderDirect.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SharpDX">
      <HintPath>$(Bin64)\SharpDX.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SharpDX.D3DCompiler">
      <HintPath>$(Bin64)\SharpDX.D3DCompiler.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SharpDX.Direct3D11">
      <HintPath>$(Bin64)\SharpDX.Direct3D11.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SharpDX.DXGI">
      <HintPath>$(Bin64)\SharpDX.DXGI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SpaceEngineers.Game">
      <HintPath>$(Bin64)\SpaceEngineers.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>$(Bin64)\System.Buffers.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>$(Bin64)\System.Memory.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>$(Bin64)\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage">
      <HintPath>$(Bin64)\VRage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Game">
      <HintPath>$(Bin64)\VRage.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Input">
      <HintPath>$(Bin64)\VRage.Input.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Library">
      <HintPath>$(Bin64)\VRage.Library.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Math">
      <HintPath>$(Bin64)\VRage.Math.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Render">
      <HintPath>$(Bin64)\VRage.Render.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Render11">
      <HintPath>$(Bin64)\VRage.Render11.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="VRage" IncludeCompilerGeneratedMembers="false" />
    <Publicize Include="VRage.Render" IncludeCompilerGeneratedMembers="false" />
    <Publicize Include="VRage.Render11" IncludeCompilerGeneratedMembers="false" />
  </ItemGroup>

  <PropertyGroup>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <PublicizerRuntimeStrategies>Unsafe;IgnoresAccessChecksTo</PublicizerRuntimeStrategies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer">
      <Version>2.3.0</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
